### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by marade** [algbio/ggcat#1]
[22:18:22 ~/ggcat]$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
...
[22:18:48 ~/ggcat]$ source "$HOME/.cargo/env"
[22:18:51 ~/ggcat]$ which cargo
/home/ubuntu/.cargo/bin/cargo
[22:19:27 ~/ggcat]$ ls -la /home/ubuntu/.cargo/bin/
total 200936
drwxrwxr-x  2 ubuntu ubuntu     4096 Oct 25 22:12 .
drwxrwxr-x  3 ubuntu ubuntu     4096 Oct 25 22:13 ..
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 cargo
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 cargo-clippy
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 cargo-fmt
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 cargo-miri
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 clippy-driver
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 rls
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 rust-gdb
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 rust-gdbgui
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 rust-lldb
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 rustc
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 rustdoc
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 rustfmt
-rwxr-xr-x 13 ubuntu ubuntu 15825920 Oct 25 22:11 rustup
[22:19:31 ~/ggcat]$ cargo install --path .
error: found a virtual manifest at `/home/ubuntu/ggcat/Cargo.toml` instead of a package manifest

Additionally (not an issue) for the paper, consider comparing to BlastFrost instead of Bifrost for the queries:

https://github.com/nluhmann/BlastFrost

Thanks for your work on this interesting tool!

**Comment by Guilucand** [comment]
Hi, I switched to a workspace project type and forgot to update the install instructions.
The updated working command is:
```
cargo install --path cmdline/
```
I've updated the README file with the correct command.

Thanks for the suggestion, we'll check BlastFrost and update the benchmarks.

**Comment by marade** [comment]
Great, this appears to work. Looking forward to testing this tool.
