### ISSUE TITLE
Plans to generate a GFA?

### ISSUE THREAD

**Issue by rlorigro** [algbio/ggcat#20]
Hi,

Do you have any plans to produce a GFA output instead of a Fasta? it would be a natural way to represent the full graph with adjacency information betw unitigs

Thanks

**Comment by jianshu93** [comment]
Hello all, is this solved? Also want to do dome downstream analysis but I learned that GFA format is widely used for this purpose. Thanks! Jianshu

**Comment by Guilucand** [comment]
Hi, now GGCAT supports the output of uncolored graphs to gfa format, using the flag --gfa

**Comment by jianshu93** [comment]
Hi how about colored， no gfa support right？

Thanks，
Jianshu

**Comment by jianshu93** [comment]
It would be extremely valuable to have gfa support in color mode and we can then easily compare with other c-DBG tools. 

Best,
Jianshu
