### ISSUE TITLE
Same flag `-f` for both `--forward-only` and `--colored-query-output-format` options in queries

### ISSUE THREAD

**Issue by fingels** [algbio/ggcat#43]
According to the README, the same flag `-f` is used for both the `--forward-only` and the `--colored-query-output-format` options for queries.

I noticed the problem when trying to use the colored query with `-f JsonLinesWithNames` (as indicated in the README) but it tried to operate the forward only option instead.

**Comment by Guilucand** [comment]
Hi @fingels,
there was an error in the readme, as the flag -f is actually mapped only for the --forward-only flag.
I fixed the issue in the documentation.

Best,
Andrea
