### ISSUE TITLE
Adding GGCAT to Bioconda

### ISSUE THREAD

**Issue by karel-brinda** [algbio/ggcat#48]
Hello, any chance that GGCAT could be added to Bioconda? This is currently the main obstacle preventing us from using it in our methods, especially if we want to embed it into any non-trivial workflow to be executed on multiple computers. Given how great GGCAT is, I think the whole community would really appreciate this!

**Comment by dwpeng** [comment]
+1

**Comment by EricDeveaud** [comment]
a release tag may help for that purpose

**Comment by karel-brinda** [comment]
Great, thanks!
