### ISSUE TITLE
Which kmer-counter is actually used when building the graph?

### ISSUE THREAD

**Issue by Blekin** [algbio/ggcat#49]
Hi! I'd like to know the abundance or coverage of unitigs. I notice that GGCAT can provide such information and I'm wondering what k-mer counter is used (standalone programme or built-in programme)?

**Comment by alexandrutomescu** [comment]
Hi! 

The abundances are computed by GGCAT (our own built-in routines during the graph construction) and are reported in the same format as [BCALM2](https://github.com/GATB/bcalm#output), namely (`i` and `f` just mean `int` and `float`, respectively):

> FASTA output header:
> 
> `><id> LN:i:<length> KC:i:<abundance> km:f:<abundance> L:<+/->:<other id>:<+/-> [..]`
> 
> Where:
> 
> `LN` field is the length of the unitig
> 
> `KC` and `km` fields are for total abundance and mean abundance of kmers inside the unitig, respectively.

**Comment by Blekin** [comment]
Thanks a lot for your reply!
