### ISSUE TITLE
compiling error?

### ISSUE THREAD

**Issue by jianshu93** [algbio/ggcat#51]
Hi team,

I have the following error for Rust 1.80.1:

error[E0282]: type annotations needed for `Box<_>`
  --> /storage/home/hcoda1/4/jzhao399/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling ref-cast v1.0.20

Thanks,

Jianshu

**Comment by Guilucand** [comment]
Hi, there was a problem with a library, the last commit fixes it

**Comment by jianshu93** [comment]
To compile on MacOS gnu C/C++ is needed:

CC="$(brew --prefix)/bin/gcc-14" CXX="$(brew --prefix)/bin/g++-14" cargo install --path crates/cmdline/ --locked

Otherwise there will be tons of errors of relying on default clang. 

It would be nice to add to readme for macOS users. 

Thanks,

Jianshu
