### ISSUE TITLE
Panic on assertion `left == right` failed while using the -c flag

### ISSUE THREAD

**Issue by yoann-dufresne** [algbio/ggcat#52]
Hello there,

I'm using GGCAT to create a cDBG on multiple Human haplotypes. To test the software I'm using 2 individuals (4 h) as input.
I'm using a file list with the 4 hapl files in it: [2_genomes.txt](https://github.com/user-attachments/files/16850063/2_genomes.txt)
list of the NCBI accessions of those hapl : GCA_018472715.1, GCA_018504635.1, GCA_018504625.1, GCA_018472765.1

When I run a build command to create a cDBG the command crash (see end of the issue for the command and error).
When I rerun bithout the -c flag everything works.

Am I missing something or is it a bug?

Thanks!
Yo'

Here is the command and the error message:
```bash
> ggcat build -k 31 -e -s 1 -c --threads-count 8 --keep-temp-files -o output/dbg/ggcat.fa -l 2_genomes.txt --temp-dir /tmp
Allocator initialized: mem: 2 GiB chunks: 8192 log2: 18
Using m: 12 with k: 31
Started phase: reads bucketing prev stats: 
Elaborated 2589 sequences! [10003553893 | 100.00% qb] (0[4]/4 => 0.00%)  ptime: 36.88s gtime: 36.88s
Temp buckets files size: 14.14 GiB
Finished phase: reads bucketing. phase duration: 45.49s gtime: 45.49s
Started phase: kmers merge prev stats: 
Processing bucket 28(+512) of [1024(+512)[R:2789]]  ptime: 10.26s gtime: 55.75s phase eta: 283s est. tot: 293s
Panic: panicked at /home/yoann/Projects/bioinfo/pangenome_coordinates/bin/ggcat/libs-crates/parallel-processor-rs/src/buckets/readers/generic_binary_reader.rs:73:17:
assertion `left == right` failed
  left: 1045238
 right: 1045234
Backtrace:   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: start_thread
             at ./nptl/pthread_create.c:447:8
  28: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by Guilucand** [comment]
Hi Yoann,
the command you executed is correct, it's a bug in GGCAT.
the cause seems to be a problem with the lz4  compression library, that in this case buffers a few more bytes from the stream, making the assert fail. 
it should not be a problem as I later seek again to the correct position in the stream. I tested a version with the assert removed and it works correctly.

Regards,
Andrea
