### ISSUE TITLE
Interpretation of the colouring information in contigs

### ISSUE THREAD

**Issue by hmusta** [algbio/ggcat#54]
Firstly, thank you all for developing this tool!

I've been experimenting with building coloured contigs and I believe I am either misunderstanding the output or build flags, or there is a bug in ggcat. I'll provide a small working example to explain.

Given these two FASTA files:
`1.fa`:
```
>1
TGGGGAGGTAACGGCTCACCAAGGCGACGATCCC
```
`2.fa`:
```
>2
TCGTCGCCTTGGTGAGCCGTTACCTCCCCAAC
```
with the following colour mapping (replace spaces with tabs):
`mapping.in`
```
1 1.fa
2 2.fa
```

I tried assembling contigs with this command:
```
ggcat build --min-multiplicity 1 -k 31 -c -d mapping.in -o contigs.fa --eulertigs
```
resulting in
```
>0 LN:i:36 KC:i:6 km:f:1.0 C:1:6
GGGATCGTCGCCTTGGTGAGCCGTTACCTCCCCAAC
```
Which I interpret as meaning that this single contig has the same colouring throughout.

However, KMC and other tools show that `1.fa` and `2.fa` share no canonical k-mers, meaning that the contig should have at least two `C` tags since the colouring should change mid-way.

Please let me know if I'm doing something wrong or if there's any other information I can provide.

**Comment by Guilucand** [comment]
Hi, thanks for the bug report!
I managed to solve the problem, it occurred only when the kmer-counters feature was enabled, because at one point I interpreted the kmer counts as color data, writing counter in the color subset.

Andrea

**Comment by hmusta** [comment]
Thank you for promptly handling this!
